---
version: '2'
services:
  dkron1:
    build: .
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    volumes:
     - ./:/gopath/src/github.com/victorcoder/dkron
    environment:
      - GODEBUG=netdns=go
    command: scripts/run agent --server --join=dkron1:8946 --log-level=debug --bootstrap-expect=3
  dkron2:
    build: .
    ports:
      - "8080"
      - "8946"
      - "6868"
    environment:
      - GODEBUG=netdns=go
    command: scripts/run agent --server --join=dkron1:8946 --log-level=debug
  dkron3:
    build: .
    ports:
      - "8080"
      - "8946"
      - "6868"
    environment:
      - GODEBUG=netdns=go
    command: scripts/run agent --server --join=dkron1:8946 --log-level=debug
